name: 'Create release.'
description: 'release create action'

inputs:
  GITHUB_TOKEN:  # id of input
    description: 'Use GITHUB_TOKEN'
    required: true
    default: ''
  title:  # id of input
    description: 'Use title'
    required: true
    default: ''
  tag:  # id of input
    description: 'Use tag'
    required: false
    default: ''
  files:  # id of input
    description: 'Use files'
    required: false
    default: ''
  rewrite:  # id of input
    description: 'Use rewrite'
    required: false
    default: false
    type: boolean


runs:
  using: "composite"
  steps:

    - name: inputs.GITHUB_TOKEN
      id: GITHUB_TOKEN
      if: inputs.GITHUB_TOKEN
      run: echo "GITHUB_TOKEN=$(echo ${{ inputs.GITHUB_TOKEN }})" >> $GITHUB_ENV
      shell: bash

    - name: inputs.title
      id: title
      if: inputs.title
      run: echo "title=$(echo ${{ inputs.title }})" >> $GITHUB_ENV
      shell: bash

    - name: inputs.tag
      id: tag
      if: inputs.tag
      run: echo "tag=$(echo ${{ inputs.tag }})" >> $GITHUB_ENV
      shell: bash

    - name: inputs.files
      id: files
      if: inputs.files
      run: echo "files=$(echo ${{ inputs.files }})" >> $GITHUB_ENV
      shell: bash

    - name: view
      id: view
      continue-on-error: true
      run: |
        gh release view
        last_relase=$(gh release view --json tagName --jq .tagName)
        echo "last_relase=$(echo $last_relase)" >> $GITHUB_ENV
        echo ${{ env.last_relase }}
      shell: bash

    - name: rewrite
      id: rewrite
      if: inputs.rewrite == 'true' && steps.view.outcome == 'success'
      run: gh release delete ${{ env.last_relase }} --cleanup-tag --yes
      shell: bash

    - name: create
      id: create
      if: ${{ always() }}
      run: |
        gh release create \
        ${{ env.tag }} \
        ${{ env.files }} \
        --target master \
        --generate-notes \
        --title ${{ env.title }}
        new_relase=$(gh release view --json tagName --jq .tagName)
        echo "new_relase=$(echo $new_relase)" >> $GITHUB_ENV
        echo ${{ env.new_relase }}
      shell: bash
