name: clean_relases
on:
 workflow_dispatch:


jobs:
  cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: cli
        run: |
         # chmod +x ./clean_relases.sh
         # ./clean_relases.sh
         git fetch
         git tag -l | xargs -n 1 git push --delete origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}