name: clean_relases
on:
 workflow_dispatch:
jobs:
  cli:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: clean relases and tags
        continue-on-error: true
        run: |
         chmod +x ./.github/clean_relases.sh
         ./.github/clean_relases.sh

      - name: clean workflow_runs
        run: |
          gh api repos/${{ github.repository }}/actions/runs \
          --paginate -q '.workflow_runs[] | select(.head_branch == "master") | "\(.id)"' | \
          xargs -n1 -I % gh api repos/${{ github.repository }}/actions/runs/% -X DELETE
