name: clean_relases
on:
 workflow_dispatch:


jobs:
  cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: cli
        run: |
         gh release list | sed 's/|/ /' | gawk '{print $1, $8}' \
         | while read -r line; do gh release delete -y "$line"; done

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}