name: clean_relases
on:
 workflow_dispatch:


jobs:
  cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: cli
        run: |
         chmod +x ${{ github.action_path }}/clean_relases.sh
         ${{ github.action_path }}/clean_relases.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}