name: release-matrix-test
run-name: ${{ github.workflow }} ✅ ${{ github.actor }} ✅ ${{ github.event_name}}
on:
  workflow_dispatch:
jobs:
  bash:
    name: release create
    continue-on-error: false
    strategy:
      max-parallel: 3
      matrix:
       os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

      - uses: milankomaj/releases-x@v0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # target: master
        # title: relase
        # rewrite: true
        # files: |
        #  ${{ github.workspace }}/.github/workflows/*.yml \
        #  ${{ github.workspace }}/*.yml
