name: release-matrix-test
run-name: ${{ github.workflow }} ✅ ${{ github.actor }} ✅ ${{ github.event_name}}
on:
  workflow_dispatch:


jobs:
  bash:
    name: release create
    continue-on-error: false
    strategy:
      max-parallel: 3
      matrix:
       os: [ubuntu-latest]


    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: milankomaj/releases-x@v0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          title: 'relase'
          tag: 'v0.2'
          files: 'file_1.txt file_2.txt'
          rewrite: 'true'
