name: release-matrix-test
run-name: ${{ github.workflow }} ✅ ${{ github.actor }} ✅ ${{ github.event_name}}
on:
  workflow_dispatch:


jobs:
  bash:
    name: release create
    continue-on-error: false
    strategy:
      max-parallel: 3
      matrix:
       os: [ubuntu-latest]


    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/upload-artifact@v3
        with:
         name: workflows
         path: ${{ github.workspace }}/.github/workflows/*.yml  
         
      - uses: actions/upload-artifact@v3
        with:
         name: composite
         path: ${{ github.workspace }}/*.yml   

      - uses: actions/download-artifact@v3
        with:
         path: ./artifacts/

      - name: tree
        run:  tree -h ${{ github.workspace }}/./artifacts/

      - uses: milankomaj/releases-x@v0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
<<<<<<< HEAD
          target: ''
          title: 'relase'
          tag: 'v0.2'
          rewrite: 'true'
          files: |
           ${{ github.workspace }}/.github/workflows/*.yml \
           ${{ github.workspace }}/*.yml
=======
          title: relase
          tag: v0.2
          rewrite: true          
          files: | 
           ${{ github.workspace }}/./artifacts/**/*
    

         
>>>>>>> 0eb0f9b7115e0e6dca3782c9affaeb37efaad671
