name: release-matrix-test
run-name: ${{ github.workflow }} ✅ ${{ github.actor }} ✅ ${{ github.event_name}}
on:
  workflow_dispatch:
   branches: 'v0.3'

jobs:
  bash:
    name: release create
    continue-on-error: false
    strategy:
      max-parallel: 3
      matrix:
       os: [ubuntu-latest]


    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/upload-artifact@v3
        with:
         name: workflows
         path: ${{ github.workspace }}/.github/workflows/*.yml

      - uses: actions/upload-artifact@v3
        with:
         name: composite
         path: ${{ github.workspace }}/*.yml

      - uses: actions/download-artifact@v3
        with:
         path: ./artifacts/

      - name: tree
        run:  tree -h ${{ github.workspace }}/./artifacts/

      - uses: milankomaj/releases-x@v0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          target: v0.3
          title: relase
          tag: v0.2
          rewrite: true
          files: |
           ${{ github.workspace }}/.github/workflows/*.yml \
           ${{ github.workspace }}/*.yml
